---
version: 2.1

executors:
  # Whenever the Go version is updated here, .promu.yml
  # should also be updated.
  golang:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

jobs:
  test:
    executor: golang

    steps:
    - checkout
    - setup_remote_docker
    - run: make promu
    - run: make
    - store_artifacts:
        path: bunnycdn_exporter
        destination: /build/bunnycdn_exporter
    - run: rm -f bunnycdn_exporter
    - run: git diff --exit-code

  build:
    machine: true

    steps:
    - checkout
    - run: make promu
    - run: promu crossbuild -v -p linux/amd64
    - persist_to_workspace:
        root: .
        paths:
        - .build
    - store_artifacts:
        path: .build
        destination: /build

  docker_hub_master:
    docker:
    - image: docker:19.03.7
      auth:
        username: $DOCKER_HUB_USERNAME
        password: $DOCKER_HUB_PASSWORD

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: ln -s .build/linux-amd64/bunnycdn_exporter bunnycdn_exporter
    - run:
        name: Login to Docker Hub
        command: echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
    - run:
        name: Build the Docker image
        command: docker build -t ricardoag/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .
    - run:
        name: Docker Push the image to the Docker registry
        command: docker push ricardoag/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH

  docker_hub_release_tags:
    executor: golang

    steps:
    - checkout
    - setup_remote_docker
    - run: mkdir -v -p ${HOME}/bin
    - run: curl -L 'https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2' | tar xvjf - --strip-components 3 -C ${HOME}/bin
    - run: echo 'export PATH=${HOME}/bin:${PATH}' >> ${BASH_ENV}
    - attach_workspace:
        at: .
    - run: make promu
    - run: promu crossbuild -p linux/amd64 tarballs
    - run: promu checksum .tarballs
    - store_artifacts:
        path: .tarballs
        destination: releases
    - run: ln -s .build/linux-amd64/bunnycdn_exporter bunnycdn_exporter
    - run: make docker DOCKER_IMAGE_TAG=$CIRCLE_TAG DOCKER_REPO=ricardoag/$CIRCLE_PROJECT_REPONAME
    - run:
        name: Login to Docker Hub
        command: echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
    - run: |
        if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
          make docker-tag-latest DOCKER_IMAGE_TAG="$CIRCLE_TAG" DOCKER_REPO=ricardoag/$CIRCLE_PROJECT_REPONAME
        fi
    - run: make docker-publish DOCKER_REPO=ricardoag/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  bunnycdn_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
    - docker_hub_master:
        context: dev
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - docker_hub_release_tags:
        context: dev
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
